"""rename title

Revision ID: 8cc9de32cac3
Revises: 27260b42c05e
Create Date: 2024-01-14 17:51:44.766553

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cc9de32cac3"
down_revision: Union[str, None] = "27260b42c05e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "thread", sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.drop_column("thread", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("thread", sa.Column("title", sa.VARCHAR(), nullable=False))
    op.drop_column("thread", "name")
    # ### end Alembic commands ###
